In [1]:
import pandas as pd
train = pd.read_parquet('train.parquet')
train.info()
train.describe()

<class 'pandas.DataFrame'>
RangeIndex: 61744 entries, 0 to 61743
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       61744 non-null  str
 1   customer_id                    61744 non-null  str
 2   order_status                   61744 non-null  str
 3   order_purchase_timestamp       61744 non-null  str
 4   order_approved_at              61734 non-null  str
 5   order_delivered_carrier_date   61743 non-null  str
 6   order_delivered_customer_date  61744 non-null  datetime64[us]
 7   order_estimated_delivery_date  61744 non-null  datetime64[us]
 8   customer_unique_id             61744 non-null  str
 9   customer_zip_code_prefix       61744 non-null  int64
 10  customer_city                  61744 non-null  str
 11  customer_state                 61744 non-null  str
 12  n_items                        61744 non-null  float64
 13  total_price                    61744 non-null  float64
 14  total_freight                  61744 non-null  float64
 15  n_payments                     61743 non-null  float64
 16  total_payment                  61743 non-null  float64
 17  is_late                        61744 non-null  int64
dtypes: datetime64[us](2), float64(5), int64(2), str(9)
memory usage: 18.8 MB

,order_delivered_customer_date,order_estimated_delivery_date,customer_zip_code_prefix,n_items,total_price,total_freight,n_payments,total_payment,is_late
count,61744,61744,61744.000000,61744.000000,61744.000000,61744.000000,61743.000000,61743.000000,61744.000000
mean,2018-01-14 22:33:39.433791,2018-01-26 03:44:17.320549,35128.314994,1.140499,137.098888,22.808992,1.044426,159.936866,0.081141
min,2016-10-11 13:46:32,2016-10-04 00:00:00,1003.000000,1.000000,0.850000,0.000000,1.000000,9.590000,0.000000
25%,2017-09-26 16:54:58.250000,2017-10-05 00:00:00,11347.000000,1.000000,45.900000,13.850000,1.000000,61.930000,0.000000
50%,2018-02-02 23:07:41.500000,2018-02-16 00:00:00,24415.000000,1.000000,86.000000,17.170000,1.000000,105.280000,0.000000
75%,2018-05-16 20:30:13.500000,2018-05-28 00:00:00,58713.750000,1.000000,149.900000,24.010000,1.000000,176.025000,0.000000
max,2018-10-11 16:41:14,2018-10-23 00:00:00,99980.000000,15.000000,13440.000000,711.330000,19.000000,13664.080000,1.000000
std,NaN,NaN,29783.665210,0.530161,211.552759,20.890201,0.358679,221.233225,0.273054

In [2]:
train.isna().sum().sort_values(ascending=False).head(10)

order_approved_at                10
order_delivered_carrier_date      1
n_payments                        1
total_payment                     1
customer_id                       0
order_id                          0
order_delivered_customer_date     0
order_estimated_delivery_date     0
order_purchase_timestamp          0
order_status                      0
dtype: int64

In [3]:
train.groupby('is_late')[['total_price', 'total_freight', 'n_items']].mean()

         total_price  total_freight   n_items
is_late
0         136.233623      22.647663  1.143230
1         146.897279      24.635914  1.109581

In [5]:
train.to_parquet('train_eda.parquet', index=False)  
print("saved!")

saved!